### ISSUE TITLE
FOSS Usage Permission Request

### ISSUE THREAD

**Issue by DuckSoft** [silver83/node-proxyconf#1]
Hello this is @DuckSoft from @Qv2ray. Thanks for you wonderful piece of work!

I would like to ask for your permission for allowing us to integrate your code on macOS proxy configuration into https://git.io/qv2ray project. Also, I wonder if you can add a `LICENSE` file to your code repository, so that we can cite this repository directly, with the LICENSE attached.

Looking forward to your reply.

**Comment by silver83** [comment]
yup, no problem. I'll try to take care of licence later tonight

**Comment by DuckSoft** [comment]
Appreciate!
